{% set name = "jupyter-rospkg" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_rospkg-{{ version }}.tar.gz
  sha256: 53b3cbc05095676d8ba2a4a321e7fb7c1f7b0c5c6b580259bcc597bb320d28b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyter_server <2,>=1.6
    - rospkg
    - notebook

test:
  imports:
    - jupyter_rospkg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/jupyter-rospkg/
  summary: A server extension for JupyterLab to handle ROS packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ihuicatl
